BUILD:
  - armv7-conda_cos7-linux-gnueabihf
cdt_arch:
  - armv7l
cdt_name:
  - cos7
c_compiler:
  - gcc
c_compiler_version:
  - '12'
channel_sources:
  - conda-forge
channel_targets:
  - conda-forge main
target_platform:
  - linux-64
zlib:
  - '1.2'

rust_arch:
  - armv7-unknown-linux-gnueabihf

rust_std_extra:
  - aarch64-apple-ios
  - x86_64-apple-ios
  - aarch64-apple-ios-sim

