channel_sources:
  - e8035669acarmv7,conda-forge
channel_targets:
  - e8035669acarmv7 main
target_platform:
  - linux-armv7l
rust_arch:
  - x86_64-unknown-linux-gnu    # [linux64]
  - armv7-unknown-linux-gnueabihf # [armv7l]

rust_std_extra:
  - aarch64-apple-ios
  - x86_64-apple-ios
  - aarch64-apple-ios-sim
  - aarch64-linux-android
  - arm-linux-androideabi
  - armv7-linux-androideabi
  - i686-linux-android
  - wasm32-unknown-unknown
  - x86_64-linux-android

docker_image:
- e8035669/linux-anvil-armv7l # [os.environ.get("BUILD_PLATFORM") == "linux-armv7l"]
