target_platform:
  - linux-armv7l
c_stdlib_version:  # [linux64]
  - '2.17'         # [linux64]
rust_arch:
  - x86_64-unknown-linux-gnu    # [linux64]
  - armv7-unknown-linux-gnueabihf # [armv7l]

rust_std_extra:
  - aarch64-apple-ios
  - x86_64-apple-ios
  - aarch64-apple-ios-sim
  - aarch64-linux-android
  - arm-linux-androideabi
  - armv7-linux-androideabi
  - i686-linux-android
  - wasm32-unknown-unknown
  - x86_64-linux-android
  - x86_64-pc-windows-msvc   # [linux and x86_64]
