BUILD:
- armv7-conda_cos7-linux-gnueabihf
c_compiler:
- gcc
c_compiler_version:
- '12'
c_stdlib:
- sysroot
c_stdlib_version:
- '2.17'
cdt_arch:
- armv7l
cdt_name:
- cos7
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-aarch64
rust_arch:
- armv7-unknown-linux-gnueabihf
target_platform:
- linux-armv7l
zip_keys:
- - c_stdlib_version
  - cdt_name
zlib:
- '1.2'
